font_family       MesloLGS Nerd Font
font_size         11.0
# Force Kitty to use the regular font weight for bold text
bold_font        MesloLGS Nerd Font
bold_is_bright   no

# Shape definition
cursor_shape      block

# Adjusts the vertical size of the text cell (and the block cursor)
# Negative values make the cell and block shorter
modify_font line_height -2

# Stop shell integration from forcing a line/beam cursor
shell_integration no-cursor

# Specific padding (Left, Top, Right, Bottom)
# window_padding_width left top right bottom
window_padding_width 12 10 12 10

